admin1/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

urlpatterns = [
    path('mahasiswa/', include('mahasiswa.urls', namespace='mahasiswa')),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('logout/', logout_page, name='logout'),
    path('index/', dashboard, name='dashboard'),
]

mahasiswa/urls.py
from django.urls import path

from .views import *

app_name = 'mahasiswa'
urlpatterns = [
    path('', mahasiswa, name='index'),
    path('create/', create, name='create'),
    path('update/<str:updateId>', update, name='update'),
    path('delete/<str:deleteId>', delete, name='delete'),
]

mahasiswa/models.py
from django.db import models

# Create your models here.


class MahasiswaModel(models.Model):
    nama = models.CharField(max_length=250)
    nim = models.IntegerField()
    kelas = models.CharField(max_length=250)
    shift = models.CharField(
        max_length=250,
        choices=(
            ('Reguler A', 'Reg A'),
            ('Reguler B', 'Reg B'),
            ('Reguler C', 'Reg C'),
        ),
        default='Reg A',
    )
    jurusan = models.CharField(
        max_length=250,
        choices=(
            ('Akutansi', 'Akutansi'),
            ('Biologi', 'Biologi'),
            ('Fisika', 'Fisika'),
            ('Ekonomi', 'Ekonomi'),
            ('Hukum', 'Hukum'),
            ('Ilmu Komputer', 'Ilmu Komputer'),
            ('Politik', 'Politik'),
        ),
        default='Akutansi'
    )

    def __str__(self):
        return self.nama

mahasiswa/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import MahasiswaModel


class MahasiswaForm(forms.ModelForm):

    class Meta:
        model = MahasiswaModel
        fields = (
            "nama",
            "nim",
            "kelas",
            "jurusan",
            "shift",
        )

        widgets = {
            'nama': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'masukan nama',
                }
            ),

            'nim': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'masukan nim',
                }
            ),

            'kelas': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'masukan kelas',
                }
            ),

            'jurusan': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),

            'shift': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'fadeIn second',
                    'placeholder': 'Username...',
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'fadeIn second',
                    'placeholder': 'Email...',
                }
            ),
            'password1': forms.PasswordInput(
                attrs={
                    'class': 'fadeIn second',
                    'placeholder': 'Email...',
                }
            ),
            'password2': forms.PasswordInput(
                attrs={
                    'class': 'fadeIn second',
                    'placeholder': 'Email...',
                }
            ),
        }

admin1/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from mahasiswa.forms import RegisterUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):

    return redirect('login')


def login_page(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.info(request, 'Username or password is incorrect')

        context = {
            'title': 'Login Page',
        }

        return render(request, 'login.html', context)


def logout_page(request):
    logout(request)

    return redirect('login')


def register_page(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        form = RegisterUserForm()
        if request.method == 'POST':
            form = RegisterUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('login')

        context = {
            'title': 'Register Page',
            'form': form,
        }

        return render(request, 'register.html', context)


@login_required(login_url='login')
def dashboard(request):
    context = {
        'title': 'Dashboard',
        'header': 'Dashboard',
    }

    return render(request, 'dashboard.html', context)

mahasiswa/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import MahasiswaModel
from .forms import MahasiswaForm


@login_required(login_url='login')
def mahasiswa(request):
    data_mhs = MahasiswaModel.objects.all()
    context = {
        'title': 'Data Mahasiswa',
        'header': 'Data Mahasiswa',
        'data_mhs': data_mhs,
    }

    return render(request, 'mahasiswa/index.html', context)


@login_required(login_url='login')
def create(request):
    form_mhs = MahasiswaForm()

    if request.method == 'POST':
        form_mhs = MahasiswaForm(request.POST)
        if form_mhs.is_valid():
            form_mhs.save()

            return redirect('mahasiswa:index')

    context = {
        'title': 'Data Mahasiswa',
        'header': 'Tambah Data Mahasiswa',
        'form_mhs': form_mhs,
    }

    return render(request, 'mahasiswa/create.html', context)


@login_required(login_url='login')
def update(request, updateId):
    mhs = MahasiswaModel.objects.get(pk=updateId)
    form_mhs = MahasiswaForm(instance=mhs)

    if request.method == 'POST':
        form_mhs = MahasiswaForm(request.POST, instance=mhs)
        if form_mhs.is_valid():
            form_mhs.save()

            return redirect('mahasiswa:index')

    context = {
        'title': 'Data Mahasiswa',
        'header': 'Update Data Mahasiswa',
        'form_mhs': form_mhs,
    }

    return render(request, 'mahasiswa/create.html', context)


@login_required(login_url='login')
def delete(requset, deleteId):
    data_mhs = MahasiswaModel.objects.get(pk=deleteId)
    data_mhs.delete()

    return redirect('mahasiswa:index')

mahasiswa/templates/mahasiswa/create.html
{% extends 'base_admin.html' %}

{% block title %}
{{title}}
{% endblock title %}

{% block header1 %}
{{header}}
{% endblock header1 %}

{% block header2 %}
{{header}}
{% endblock header2 %}

{% block content %}
<div class="container">
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        {% for form in form_mhs %}
        <div class="form-group">
            {{form.label}}
            {{form}}
        </div>
        {% endfor %}
        <br>
        <div class="container">
            <div class="row">
                <button class="btn btn-primary" type="submit">Kirim</button>
                <a class="btn btn-success ml-3" href="{% url 'mahasiswa:index' %}">Kembali</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

mahasiswa/templates/mahasiswa/index.html
{% extends 'base_admin.html' %}

{% block title %}
{{title}}
{% endblock title %}

{% block header1 %}
{{header}}
{% endblock header1 %}

{% block header2 %}
{{header}}
{% endblock header2 %}

{% block content %}
<div class="container">
    <br>
    <a class="btn btn-info" href="{% url 'mahasiswa:create' %}">+Mahasiswa</a>
    <br>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">No</th>
                <th scope="col">Nama</th>
                <th scope="col">Nim</th>
                <th scope="col">Kelas</th>
                <th scope="col">Jurusan</th>
                <th scope="col">Shift</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for mhs in data_mhs %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{mhs.nama}}</td>
                <td>{{mhs.nim}}</td>
                <td>{{mhs.kelas}}</td>
                <td>{{mhs.jurusan}}</td>
                <td>{{mhs.shift}}</td>
                <td>
                    <a class="btn btn-warning" href="{% url 'mahasiswa:update' mhs.pk %}">Update</a>
                </td>
                <td>
                    <a class="btn btn-danger" href="{% url 'mahasiswa:delete' mhs.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/base_admin.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    {% include 'snippets/styles_admin.html' %}

</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        {% include 'snippets/header_admin.html' %}

        {% include 'snippets/sidebar_admin.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    {% block header1 %}
                    {% endblock header1 %}
                    <small>Control panel</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">
                        {% block header2 %}
                        {% endblock header2 %}
                    </li>
                </ol>
            </section>

            {% block content %}
            {% endblock content %}

            <!-- /.content -->
        </div>

        {% include 'snippets/footer_admin.html' %}

    </div>
    <!-- ./wrapper -->

    {% include 'snippets/scripts_admin.html' %}
</body>

</html>

templates/dashboard.html
{% extends 'base_admin.html' %}

{% block title %}
{{title}}
{% endblock title %}

{% block header1 %}
{{header}}
{% endblock header1 %}

{% block header2 %}
{{header}}
{% endblock header2 %}

{% block content %}
<div class="container">
    <h1>Selamat Datang Di Iyan Admin</h1>
    <br>
    <p>Ini Adalah Halaman Dashboard</p>
</div>
{% endblock content %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% include 'snippets/styles_login.html' %}
    <title>{{title}}</title>
</head>

<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->

            <!-- Icon -->
            <div class="fadeIn first">
                <!--<img src="{% static 'img/Logo.png' %}" id="icon" alt="User Icon" />-->
                <br>
                <h2 style="color: black;">LOGIN</h2>
            </div>
            <!-- Login Form -->
            <form method="POST">
                {% csrf_token %}
                <input type="text" id="login" class="fadeIn second" name="username" placeholder="Username">
                <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">
                <input type="submit" class="fadeIn fourth" value="Log In">

                {% for message in messages %}
                <p style="color: red;">{{message}}</p>
                {% endfor %}
            </form>

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <p>Don't have account? <a class="underlineHover" href="{% url 'register' %}">Sign Up</a></p>
            </div>

        </div>
    </div>

    {% include 'snippets/scripts_login.html' %}
</body>

</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% include 'snippets/styles_login.html' %}
    <title>{{title}}</title>
</head>

<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->

            <!-- Icon -->
            <div class="fadeIn first">
                <!--<img src="{% static 'img/Logo.png' %}" id="icon" alt="User Icon" />-->
                <br>
                <h2 style="color: black;">REGISTER ACCOUNT</h2>
            </div>
            <!-- Login Form -->
            <form method="POST">
                {% csrf_token %}
                {{form.username}}
                {{form.email}}
                {{form.password1}}
                {{form.password2}}

                <input type="submit" class="fadeIn fourth" value="Register">
                <div class="container">
                    <p>{{form.errors}}</p>
                </div>
            </form>

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <p>Already Have Account? <a class="underlineHover" href="{% url 'login' %}">Login</a></p>
            </div>

        </div>
    </div>

    {% include 'snippets/scripts_login.html' %}
</body>

</html>

templates/snippets/footer_admin.html
<!-- /.content-wrapper -->
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All
    rights
    reserved.
</footer>

templates/snippets/header_admin.html
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>I</b>A</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>IYANS</b>ADMIN</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

            </ul>
        </div>
    </nav>
</header>

templates/snippets/scripts_admin.html
{% load static %}
<!-- jQuery 3.1.1 -->
<script src="{% static 'plugins/jQuery/jquery-3.1.1.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="plugins/morris/morris.min.js"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/knob/jquery.knob.js' %}"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

templates/snippets/scripts_login.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
</script>

templates/snippets/sidebar_admin.html
{% load static %}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% static 'img/user.jpg' %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{request.user}}</p>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                            class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href="{% url 'dashboard' %}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{% url 'mahasiswa:index' %}">
                    <i class="fa fa-graduation-cap"></i> <span>Mahasiswa</span>
                </a>
            </li>
            <li>
                <a href="{% url 'logout' %}">
                    <i class="fa fa-sign-out"></i> <span>Logout</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

templates/snippets/styles_admin.html
{% load static %}
<link rel="icon" href="{% static 'img/Logo.png' %}">
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
<!-- Morris chart -->
<link rel="stylesheet" href="{% static 'plugins/morris/morris.css' %}">
<!-- jvectormap -->
<link rel="stylesheet" href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">
<!-- Date Picker -->
<link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">

templates/snippets/styles_login.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="icon" href="{% static 'img/Logo.png' %}">